# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

DEFINES		:= -DARM9
SOURCEDIRS	:= arm9/source
INCLUDEDIRS	:= common

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile.arm9
