# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

DEFINES		:= -DARM7
SOURCEDIRS	:= arm7/source
INCLUDEDIRS	:= common

LIBS		:= -lnds7 -ldswifi7 -lmm7
LIBDIRS		:= $(BLOCKSDS)/libs/libnds \
		   $(BLOCKSDS)/libs/dswifi \
		   $(BLOCKSDS)/libs/maxmod

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile.arm7
